version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - BACKEND_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - PROCESSOR_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - FRONTEND_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Docker images...
      - cd backend && docker build -t $BACKEND_ECR_REPO_URI:$BACKEND_TAG -t $BACKEND_ECR_REPO_URI:latest .
      - cd ../processor && docker build -t $PROCESSOR_ECR_REPO_URI:$PROCESSOR_TAG -t $PROCESSOR_ECR_REPO_URI:latest .
      - cd ../frontend && docker build -t $FRONTEND_ECR_REPO_URI:$FRONTEND_TAG -t $FRONTEND_ECR_REPO_URI:latest .
      
      - echo Pushing images to ECR...
      - docker push $BACKEND_ECR_REPO_URI:$BACKEND_TAG
      - docker push $BACKEND_ECR_REPO_URI:latest
      - docker push $PROCESSOR_ECR_REPO_URI:$PROCESSOR_TAG
      - docker push $PROCESSOR_ECR_REPO_URI:latest
      - docker push $FRONTEND_ECR_REPO_URI:$FRONTEND_TAG
      - docker push $FRONTEND_ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Creating task definition files...
      - aws ecs describe-task-definition --task-definition sp-01-backend --query taskDefinition > backend-task-def.json || echo "Task definition not found, will create new one"
      - aws ecs describe-task-definition --task-definition sp-01-processor --query taskDefinition > processor-task-def.json || echo "Task definition not found, will create new one"
      - aws ecs describe-task-definition --task-definition sp-01-frontend --query taskDefinition > frontend-task-def.json || echo "Task definition not found, will create new one"

artifacts:
  files:
    - backend-task-def.json
    - processor-task-def.json
    - frontend-task-def.json
    - appspec.yaml
    - scripts/**/*