version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker images...
      - docker-compose build --no-cache

      - echo Tagging images...
      - docker tag sp-01-backend:latest $BACKEND_ECR_REPO_URI:$IMAGE_TAG
      - docker tag sp-01-processor:latest $PROCESSOR_ECR_REPO_URI:$IMAGE_TAG
      - docker tag sp-01-frontend:latest $FRONTEND_ECR_REPO_URI:$IMAGE_TAG

      - echo Pushing to ECR...
      - docker push $BACKEND_ECR_REPO_URI:$IMAGE_TAG
      - docker push $PROCESSOR_ECR_REPO_URI:$IMAGE_TAG
      - docker push $FRONTEND_ECR_REPO_URI:$IMAGE_TAG

      # Update latest tags
      - docker tag sp-01-backend:latest $BACKEND_ECR_REPO_URI:latest
      - docker tag sp-01-processor:latest $PROCESSOR_ECR_REPO_URI:latest
      - docker tag sp-01-frontend:latest $FRONTEND_ECR_REPO_URI:latest

      - docker push $BACKEND_ECR_REPO_URI:latest
      - docker push $PROCESSOR_ECR_REPO_URI:latest
      - docker push $FRONTEND_ECR_REPO_URI:latest

  post_build:
    commands:
      - echo Creating task definition json files...
      - aws ecs describe-task-definition --task-definition sp-01-backend --query taskDefinition > backend-task-def.json
      - aws ecs describe-task-definition --task-definition sp-01-processor --query taskDefinition > processor-task-def.json
      - aws ecs describe-task-definition --task-definition sp-01-frontend --query taskDefinition > frontend-task-def.json

      # Update image URI
      - jq '.containerDefinitions[0].image="'$BACKEND_ECR_REPO_URI:$IMAGE_TAG'"' backend-task-def.json > backend-new-task-def.json
      - jq '.containerDefinitions[0].image="'$PROCESSOR_ECR_REPO_URI:$IMAGE_TAG'"' processor-task-def.json > processor-new-task-def.json
      - jq '.containerDefinitions[0].image="'$FRONTEND_ECR_REPO_URI:$IMAGE_TAG'"' frontend-task-def.json > frontend-new-task-def.json

      # Register new task definitions and update services
      - aws ecs register-task-definition --family sp-01-backend --cli-input-json file://backend-new-task-def.json
      - aws ecs register-task-definition --family sp-01-processor --cli-input-json file://processor-new-task-def.json
      - aws ecs register-task-definition --family sp-01-frontend --cli-input-json file://frontend-new-task-def.json

      - aws ecs update-service --cluster $CLUSTER_NAME --service $BACKEND_SERVICE --task-definition sp-01-backend --force-new-deployment
      - aws ecs update-service --cluster $CLUSTER_NAME --service $PROCESSOR_SERVICE --task-definition sp-01-processor --force-new-deployment
      - aws ecs update-service --cluster $CLUSTER_NAME --service $FRONTEND_SERVICE --task-definition sp-01-frontend --force-new-deployment

artifacts:
  files:
    - backend-new-task-def.json
    - processor-new-task-def.json
    - frontend-new-task-def.json
    - appspec.yml