version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    env_file:
      - .env.example
    depends_on:
      - processor
      - db

  processor:
    build: ./processor
    env_file:
      - .env.example

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env.example
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: logjack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: